### ISSUE TITLE
Can't fetch just one football game

### ISSUE THREAD

**Issue by austinmbrown** [stattleship/stattleship-ruby#6]
Based on the documentation [here](http://developers.stattleship.com/#football-games), I tried to do:
```
query_params = Stattleship::Params::FootballGamesParams.new
query_params.id = game.stattleship_id
```
but I got:
```
NoMethodError: undefined method `id=' for #<Stattleship::Params::FootballGamesParams:0x007fd8ce543770>
```

So then I figured out that I could do:
```
query_params = Stattleship::Params::FootballGamesParams.new
query_params.game_id = game.stattleship_id
game_response = Stattleship::FootballGames.fetch(params: query_params)
```
But then I got this error:
```
ArgumentError: expected game_id to start with 'nfl'
```

So then I did:
```
query_params = Stattleship::Params::FootballGamesParams.new
query_params.game_id = "nfl-"+game.stattleship_id
game_response = Stattleship::FootballGames.fetch(params: query_params)
```
and I got the entire season back instead of just a game. Think that's a bug, or am I doing something wrong?

**Comment by dthyresson** [comment]
@austinmbrown You're right. While the API itself supports a single game query via the `games` endpoint:

```https://api.stattleship.com/football/nfl/games/nfl-2017-2018-det-nyg-2017-09-18-2030```

The Ruby gem doesn't implement that query.

Note: the id is in fact the game's `slug` (all ids are in fact slugs, including `player_id` and `team_id` etc).

Note: this will return a single game w/ json of `game: <>` rather than `games: <>`.

An oversight, for certain, but also the `games` ep is for a schedule of games, so it is rare to fetch just one game.

Instead, the `game_logs` and other ep's do support a `game_id=<slug>` to return the stats for just one game.

If this is a blocking item, let me know and I can implement that set of params for a single game query.

**Comment by austinmbrown** [comment]
Cool, thanks for the info. I ended up grabbing the games by week for that particular call, so it's all good.

**Comment by dthyresson** [comment]
Ah, that makes sense for 🏈 -- to get the games for that week. For other sports, most people fetch the games on `today` or `tomorrow`.

I'll keep it as an enhancement since the API does support the single-game fetch and so the gem should, too.
